---
"353":
  countdown: 5
  consume: true
  message: "§bWell done ,you have a Speed"

  effect:

    1:
      durability: 20
      amplifier: 2
      visible: true

"351:1":
  #The waiting period of the next use of the item in sec
  countdown: 0
  #Allows to have only one use per item
  consume: false
  #If you don't want a message put null
  message: null

  effect:

    #The id of the effects
    6:
      #Allows you to add the time in sec to the effect
      durability: 1
      #Allows to add a specific force to the effect
      amplifier: 1
      #Allows you to set yes or no particles to the effect
      visible: false
...
